### PR TITLE
Create variant label

### PR DESCRIPTION
**Pull request by kshefchek**
- Creates a variant node label, replaces where clauses with new label
- Makes gene interactions and homology directional, this will require a slight alteration to the query in biolink but should improve loading time

### CODE REVIEW

**Comment by TomConlin** [comment]
Sorry for the delay, trying to quickly learn enough cypher to write a legit +1.

+1

**Comment by kshefchek** [comment]
Noting here that I reverted making interaction and homology data directional, because the data in scigraph sometimes contains cycles for these edges, we ended up with duplicate documents in some cases.

**Comment by cmungall** [comment]
You mean assert in both directions? Seems reasonable

**Comment by kshefchek** [comment]
@cmungall yes, on production we index solr documents in both directions for symmetrical relationships.  I tested out on beta removing this to save on indexing time and index size, but then we ended up with a mixed state.

**Pull request merged**
